[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "f755101ed04e781b006f8e72ddcfc6617abebeac"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "2ad2a7c7e3695dfa90806caab50a9a02bf357591a885fbd4b054b1c0f60bd5de"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "5b5e8cf96ad33c94d080223222abbc56beb53d5c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "8c5fb513747690b8d55e827330c11b76018fc356ab9fde137750666692c3c546"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "c1421c030da1f541cd0cd58daa12e66fa41c2216"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "76cbaecc4c34a7ffd38fc443c50798c29d518e35507264e188b3040849043fab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "cccf8193eee8f49639af07dfb8b0ff101f2bec14"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "99365f75c73740b6a212c5b18cd7f6086053b3a3f013768dbf38aff7d9e8cd0b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "a03d1c2613d45282b15022889dd67e53b24c6330"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "d5ee7d367e66c249120ceb9ca8ede6eba8bbbe8013edc0e3f45ccee0a1fb27f2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "65402fa44502137d72602c31740b63394b6818ad"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "70a2ace18792251b62f384fdb60d10a8000a26ca0426c323746d0922c4ce2684"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "220c66adf0fdd62ba9093145b29222e3157790cb"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "3628c697fbb2dfbfc6f0dddf516538e91e2487d609e2f6f47b6c52e3f2a741be"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "5664600534c5b65fb4dc592a3b16fcf3b1e8f572"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "3cd26badcb4bd0f8bf6e5faf1551de6fa80a1ee5d22252c43d60da09c1b699d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.501+0/GAP_pkg_cvec.v200.700.501.x86_64-unknown-freebsd.tar.gz"
