[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "f644fb931dfe3eb74940fe80d05ab9dd950a8ed7"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "cf392e58a4a099df21ae5e29133d87d538620f0cee2f1f434298f94aa5f95b9e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "810d86158db37624214bf063ac955b841c2229df"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "8546ac389cbed4bb0306319ec8f88a39be33ff390cd58180dd1829ef94603816"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "8cb3ec08c53299227d3ecc0b3a2888e0faccc766"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "edc7b7cbb29cd3c493c5def59afc2b2d9dc168552c7335283f012ef8634ed7fc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "6d99d109c538a131f4cce12867a2b09e1b7e573d"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "f09c1ac1f18eceb0447610649bfa3a9e246e936caba7cc9cf29e15cc93e76be4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "3cac14ddf4306a04917eaaf496adb94d906bb087"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "2f5c37329c7fbbad97238f6eeb131089541feb976f5094b506464919da1fea93"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "riscv64"
git-tree-sha1 = "4eb14276ad88587e78a3feb511b5bf5f99f02da3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "d027b530ebfe0af8dcd91e8837df03acd29d1aa6346031e515a36e6b3218d742"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "3f110ba6b1d6772317a990af35caecf48aacb064"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "0f33a5407bfdb67b8145d78b25eb3499577a3c3c873472d2b885fe819c9675f5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "9a615fd9357ffcdfe20009387e189303f4e7ab6d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "3448fc06e7eac5feb857f2a169b4191265cd7defa6c2ff1511e0877b640d6e3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "d969f58469b12d8fca8b604f51e0c517c661aeb0"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "1d0f792ce0f805ef27494719c79d1b49840f3417883acbd96df770992f4f539e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "05f97f30679256daf581c269a6f9f2e246b4c45a"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "c5d3412415b99703eb2c58ae3a05fb9c43cc523349653cc14834fefd27550c16"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.202+0/GAP_pkg_cvec.v200.800.202.x86_64-unknown-freebsd.tar.gz"
