[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "b491aadf7310c5f63dcb66798c036b792446a354"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "20145c12d12c25a00f8fa8da8721570ef86e58fd55bb30df45b0b2436b5d7191"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "cad8c265cfe70e13f4d4d98266d829b06d2a714b"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "27748837999b57fc2a63ec70dc37a5d1cbd8f54314361080081fd2669f49d6f8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "55d09fda82a9ad9d3f6a8bdf195017646bdd73da"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "3d0f3bc47c708f82cc0b28170cdc6373017cd76e735429f4bb722bf8dc18d3db"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "fc0fdbd27188f5a2c4365d4a9d416854b09d90cc"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "f8b570d3d9c4b9bb81f7e0e12aea585543d4af90b540a593592cbc928dc4724d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "deec8fd110717425cdf5b892756a48c18430f53c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "873e2a11032b9a417f7b93133ce9dd26ea57377b62177c80fc03adcc7d9898fa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "00576592a362d24310076e9b51115ad454d7a0ec"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "14b546aedf458ffa11eb34146da1beaa0451353c0fdc71595c5a090d0b658994"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "6680384e0f47ba6f72bb3ef20db5e2c059b505db"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "3b8720c2e23f0c0ad9afd34e1feabfead605a8b99cbf820536152f4dbb6cfe1c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.500+0/GAP_pkg_cvec.v200.700.500.x86_64-unknown-freebsd.tar.gz"
