[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "4350b271a88fee473686098791b0ffc66636829e"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "1f268eb75482a1592cbf39a7d5c6ea62c7ab5509adbe777b1dfe861d674f4457"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "c69ecab7b499bc0f28bb013752fa7eeb691c4b0b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "352a94771edf6da70414104dd181a95a0eff3733318fc701bfc1703e307b5fe9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "d13793125dca84cb24cbf22b5a20a9bef22500f1"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "d769c9873b7720a63f67e335cf8c102519f91235f148a670647bd3f9646b05f2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "ca5e2ad4f6d604f48e566503bf78a9ef8959bd59"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "087707031b67d9cb78d7c896fbf3ee64b9a76245a38b734055806e6493307fc7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "f917150be622654526fc6a864138bc8cd8fc4af0"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "ca3f78aec988e99594d053cc30a67877732d345bc00f1cf7c959fec251fc8540"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "1bbd193b76faf80bf3aa8e14581d59260aa08c60"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "5a670bce4e79c9125089bf403635fb9b0a5ad08e51dd44e1e8fb862878710f8f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "08a48693e749ef2dae5ec60e77bc2b57a81ed227"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "3bc9bcd6470a9614569d70acd1e5d5fd2858ef4331047ee05805487e62003c88"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "f7258a2c8aeb114262097b73db909fa2eeff399e"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "717b2214d97de55a98e08e66e54b8157f24e898d7a97ac6cdb785fdd479e95a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+0/GAP_pkg_cvec.v200.700.600.x86_64-unknown-freebsd.tar.gz"
