[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "7f4f9f878cb2319aecfdba37bac212aeaf5143ed"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "758ab44313cc28c29524f0ee1b14dd115f38f59d295252cfd402e5f0dbce9690"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "d36e4a262dbbc36883425770bf95965beafdf17f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "0d7c45a1cb050882524a75450d30d346d8ea16f4b05f1b0249a67923ab014538"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "19fed8b9702049e4a0e3e1945600ccc7f0492048"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "41de15f6447ccad749652df222d524662e326961d1dff165b76fbc02f322388b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "85aff2b396cc6e773813ee14212d5c21e57ec950"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "545106e5641efdb876cb8867251badc0dd2504c87d4cf6142e468636ce97cd55"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "425d75572176787a557e24bd6675da83dbfed294"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "cdbd2c05e2d0f4c6b2d6032930b252c6084f6d313ece1b6fd3d6e11ffddd48c4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "riscv64"
git-tree-sha1 = "ed3d0ef41b0eb129ffaf4ce7bea1e892e4d5e074"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "58c742a0e93534bf43534f7e175642ce3333c8882c9ce859cbd538c7e4015f2a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "c595426cb66538181956666bfb1b5939db44e159"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "ba160e983fe832bf54e70e688d89e5bdf29d14101c3be379abc230d548fe8970"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "b08bcd8482a410cc5b9c83ac71e0387a435ff0f8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "e3e998a8b3079961cc0d6451e049e554b7b485283a74899b5fdcdaf86e2c7bdb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "ac01e5abd0259780380abc306ff4ae64e338bf36"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "6833161d7f2fac0c9d6f924cc0d074f1b6eece2a2cff276b3acca03f50672604"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "68aaf83740267a76487c17e8448129fedee52c9a"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "a0aa60ab8edb991bf9f23cb690d0d17bce1d817b13987e40b0cb8834f0bc5672"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80400.0+0/GAP_pkg_cvec.v201.80400.0.x86_64-unknown-freebsd.tar.gz"
