[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "d51f6b7153b409b79053803c9eab12cbe5bcf9f5"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "70263ea333c1d275d5e8dfbb86b58344da8099031d0148d370e44c78aeb8ed6b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "b971c4c1deaa99a7da94e836a0a29775f8177042"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "ddfa05d8592b632aa3dc0eeae2cc6f55c57c74a9e55de4b7f19b5fb12fd55ce9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "29a1779b4304e8101a666297d934274fe4cc1848"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "7762d5bdee8e32003b9a0d889e0a18431d46cac6bd8dfd5d10e00c1f46ba7ad6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "7f7f5a8cd38051e44b4dd8da963a6589bf4afe8a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "2f436efa5e7ba6c8954d8cf1e331131e4727db14b5801617d73cc99abe9f0db1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "0db722b841ee78087f4ff1bbfa0a0a5d232a1cbb"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "5a739a7f6cdd347e78c5170dea801f84d599529c138906ef3e8bb891716f4049"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "6a77e1239070fe4d3504e5060264863a31414449"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "59597d8ed9859b14c84bb82cbfb0572988f07f4b5d7c2f13f910d91318bb58d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "d8b959784e12862fec7f15e996086dfddfcba5d4"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "3438f4cc3b67e2437cdaeda98afda50f5b16546313abb6282ab746ed733629e6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "6846589b2172370527c52f6d4e20d18bbf8d154e"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "dd174f6dbcd3dbe4be446de5c4a064b0820bd7c480df8a43903bb6f910ea11dd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.600+1/GAP_pkg_cvec.v200.700.600.x86_64-unknown-freebsd.tar.gz"
