[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "c29ea474901ea9b36a42eb70893c5c919cad98b9"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "42d6d34af6fe1a8701a6732176d0b9df42984d662c3165c4ff16d22eb8d5e3d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "0f84c869bbc8c5f7c20ac6c2f7b26da608ae00e7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "50f74028f0305555689682a7ae79af482b776a6347f525f2d73854f298fbec6c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "75dc7d6eb8611e52fedf9ce553237b0c96b4db55"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "b8ec6725e76805252589e9799ca4e298458d7fe8fbe47e553795563e1b4ca90c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "c84e1fc592589ba74485f2421bd8645d5f9f7f3d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "2341f26f2bd0b98c3f8e1d2853abb062631d254544ae5bc5e55a627c51f5090d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "0c9e7128626d67e8d7f5f4c8eaacc9a589433ccb"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "3a24b571a60a21ee41e8093766e2313fc7dfd962a0fa17de823af9149e199cd1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "20a0c68fea41554b729f4207f80c06f80800b4d9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "9e69cfcbf5d904c1a1a0d05ec9d3e4780d157d7a05ee8b7c36ef3c3afcb8d084"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "28bc7871a121b85f3d79d9bd57e336a1aad05306"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "d23c0e219c4bba1572032bb1b49e7507f637b9383ea95aa28d6830405b4f3aec"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "718396eee4535060c57c7b2024ac3e82099e4635"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "8f0474a2d6edc2d66d9c49ce869deaeada5e83b1d4ad443a637d77ca1e240752"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+0/GAP_pkg_cvec.v200.800.200.x86_64-unknown-freebsd.tar.gz"
