[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "3d2d32f4ac833f7f11f19e5de6a1f13f6a7ff876"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "278ffd4304165c8465b5b085a9e717cc4cc8feb3435052033e2e10a5fad741b4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "cbd93f2781fc8e2f225ea504df06545d7c5e5887"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "0037c2bc5965422af01d1a1566024d9a29b43dc9b1f0e2a5aea0b94b6b9c95b3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "26729d26dc29220369bd33e040c5bdbea95de793"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "4c2329da6de3d39cb5628a33264357b0673ebd459ff77e7c5c12f5f329611bc7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "43de91beec4d31b95933fa0c4f22af4be3d83f3d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "dfc16b9a5465d8208ade39c7aca31f33c08e14c467b5370f8d1f88265b061f5c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "66e3a5389bd84d7f477f01e8d4ac6ed4af9774f7"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "d6460d7eb4948b58ac3389b81d44611a8b3eb554f1607eadd268419e463bbf46"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "68539434b2622991564c52b2aa8dc27a631d0e23"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "a3bfdaec8b1a82a68cf2fa250015561b4425e9b98cd801133e473e30412402aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "71cc0edc5c22afb1853a92cb7259a3e433dd2998"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "0efb11edf7e2f9ca128aa0e25cac4bfe318d0cd9c9780203f4662fc5eb48c0ee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "38c21135a007349717d89a23ab362c0c26be882b"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "45eade7a496a5b4bdc7de38b7f65efb62957c7dd01ff125ebdae69bc3939209f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.100+0/GAP_pkg_cvec.v200.800.100.x86_64-unknown-freebsd.tar.gz"
