[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "d47a6a5fb4888f4c2cca01ec98749dc053b2f498"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "5b072d6c0c545e850a09cd58f991d816ff8b0a8f9f6893afb8e0bd56ba9ed6bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "1f6b04c89fb0500c6b1a76625b0dc5994ba2c297"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "5aebe9c5fb0aeaa18982946c850a302f44df5e683f0ec0fbef47e9f845e4c668"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "04175a4a008c3a3ccd5aabce763e79e15f1f2dce"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "b490f236563768f5f78a1b7573d25d2576222d67dfa99135294be7c57d18a10e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "98a1d2c7d557f34c321b0a60dd4d9f770886ce77"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "50f4afba4635d7009c0197468fa713ae5edd2af12b4bbcf63b6120a2ebcc3efa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "dad6deaf0fee5c908803e6dcb3aabe018ac5a0b8"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "f4d992aac71e6709cbda28d24d4f9de8900b47196fc764a1a4630c400fd10229"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "fdfc6db8b1c0f1469ea44fea32bcf124b4d194dc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "914758c32820378006d2727b03a145a1ec8c986c48734a4aa40135ab32c4a340"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "418186ed625304718d2140f0c03fc7ed702bac37"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "13a8d1d1c0ad08b0d469ff90c3f2cf75eb5f45de1fc39ea7aa1d73d99a530fa1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "00b433d541549e74f941d623d7925d5446a0418a"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "3dce3c59a2245b3746116c9fdd993291ca5b6b4d7dfd1a1386787db5fdd6416b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.601+1/GAP_pkg_cvec.v200.700.601.x86_64-unknown-freebsd.tar.gz"
