[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "d0d85ff55ee024e61e8fa3e7a5e5b0c8ff9d6c8a"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "ac18a02b7af32e0da39c9c4b498150a4b9abda4946abc7fae6428933eb8a3e66"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "43fc4b96f91a38e5f03ec05f622409db8a8fa1e1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "97de03e921c6e5b295baacbe20257e25021efb649a5939364cd752ad9b9b9393"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "55e764b41a31e28f0e2f8c4a1deecd0f477031b7"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "921a75abd20f3caff12ebd15d89c452bffaceb93a9036bccf39ce61383ac4da1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "bf271601ac49b2c808541bff0d680f6e6e43f838"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "e4919185cb9f22cf7e401beb5b3bdc0ab0a93362887c13ec8aac5e90795cf7bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "9b9a19f3a6897b0ae78ea121f75bcc8ca2e3931d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "31c706039ee9e431da032a331f0f555a4d76ed7cae10e680f52c3b1b93735ae5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "riscv64"
git-tree-sha1 = "354f66e7919c06e958e450c2dcc7cd4fa44b2fff"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "5553793a94d3817be51343cd524b90b915351f40fa48a111a9a2fda24d16ef47"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "b2832c902b8b063622519e41e5f00c19cface03a"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "8a0a681ccc610269164483844c617e16d00537adbdadf30e1845d1e2f63f91f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "ecd63afbcab4d8942758929aaad36d566d56c43d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "0c6ed63458b87baa7826213bff8ed8fddd610ebc4b4445d361ecfe9654f14726"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "3a510e4613e868562ba6933ac7ed9146045215c7"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "45c628688ea7654b9132bf14f2ea8287e8f39026c5044821454e7829f4f84ea7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "2f617bbbca244d4eccfa27feb922e075e11012df"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "d7b555f25de36a914dfaf1decb4099d52a79cb53add53a7c40e0ebb47b0b029d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v201.80500.1+0/GAP_pkg_cvec.v201.80500.1.x86_64-unknown-freebsd.tar.gz"
