[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "149b5ba20c2249b8a3be2ed64850ee102302d56d"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "83f6bd4318f8d4f7df5dda44724a62007b38edc095531f4402d1ceacfa5450e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "a97ec238e9eac009caa6ece73199bf11f046f9ef"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "9d7ecf0fd4adcd23316439ae7e70d09f2927017fe956efd49f84646fa3571548"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "e003ba8a201355f59a1b92a91d50cd46e790471b"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "14013c15720a17317a949f3a17a8d9346391ea675190d483eec3504cb2315b96"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "6610fcb33227453df0cbe0629b64a84f4189ebd5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "7ebcfa1ebb41aba853a026638c4bd4c27e85acd9f8a4c208e853d4c3e2d1d1e0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "eaadfba8bbc17d8146400200f378f538adcc2742"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "a44870ef238268203f391402334d14431a1a39408349b6f6bde5f30382682412"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "289239795cd31f8653a887347d296f8cfd88872a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "aaed728f88bf8740f0634c6ea606a50638ed5edfbaf5ea47e8d677c6e92f529a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "ef8aacec1ad59f70252a55a6938de3f2d45fa8ab"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "05ff3dae3243caa6228c2b9ef6f5d8886e4a69f1d9d46c9106f3b38bfa418272"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "f72f8a942ae1399f2e9affc903a9f5fdd9358161"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "4abf160e7f839454447bfa8981f7318ae007eef0e9cdc537114020629bb001f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.800.200+1/GAP_pkg_cvec.v200.800.200.x86_64-unknown-freebsd.tar.gz"
