[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "d2fa8fda5d83ce66e12bf7695b4778428a1cd7d6"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "1fd29776610824b9ebc5b1635965d0d06a5453dafaca7daf4aaf82eb8137d7df"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "bae8ccd83dddb14844bc74212cc87b03d8353013"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "8f2c8524c605181490700739b35981f0812286a9ddd510f9fa4fda3127a5ab40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "aarch64"
git-tree-sha1 = "84c19ba6ecffcfae2025d41a8c0c2c78445e072a"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "fd917d5d5b98d1a17e45fa9dc44dda2710beb0e251b83b0aeae49de12f1bf96c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "powerpc64le"
git-tree-sha1 = "3f09e4e6b76beabd1c89981df3aa16421869ff64"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "53289c34912d763bc0d7d07d17587780243b5dda1e36ff6c2009490016ad4a9b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "c9a064e1886a993825e44531dfafa6944ff657b3"
os = "macos"

    [[GAP_pkg_cvec.download]]
    sha256 = "ac233a78c431dd8dd0aedaa488824d0e14fb2f65c453c79b8908ecd42b96b31b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "7d06167d637f174cc897c2f89ef7d653adde77bc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "66aad6d9c93fa608d39a9b693d8c270992ee31a92dc3185c1e84fbe4b23b5df3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "848ebe7d78d58ec1e72c56cdf68fecc0091da543"
libc = "musl"
os = "linux"

    [[GAP_pkg_cvec.download]]
    sha256 = "cbb0cbd64150dbfd62c55222f84a63da4d59e60588ca32f7cf2a426f25cfa6bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cvec]]
arch = "x86_64"
git-tree-sha1 = "00b433d541549e74f941d623d7925d5446a0418a"
os = "freebsd"

    [[GAP_pkg_cvec.download]]
    sha256 = "3dce3c59a2245b3746116c9fdd993291ca5b6b4d7dfd1a1386787db5fdd6416b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cvec_jll.jl/releases/download/GAP_pkg_cvec-v200.700.602+0/GAP_pkg_cvec.v200.700.602.x86_64-unknown-freebsd.tar.gz"
